### ISSUE TITLE
high ascii character bug

### ISSUE THREAD

**Issue by broomdodger** [applidium/Vim#21]
high ascii character bug

Prepare to see the characters:
:set enc=utf-8

Enter some high ascii characters, it is easy, for à hold down the a key until you see other characters, then slide your finger to the desired character.

àèìòù
äëïöü

Move cursor up down left right to see characters disappear

I found this when I mapped:

ino <bslash> <bslash>
im à <esc>

Easier for me to press, hold, and slide on the a key than to go 2 levels deep for the <bslash> key to do escape.

Bill

**Comment by nicolasbraun** [comment]
Follow up in #28
