### ISSUE TITLE
Change Esc key from \ to ` by default

### ISSUE THREAD

**Issue by joebologna** [applidium/Vim#24]
Using \ as the default Esc key makes it pretty hard to write code. I suspect a lot of people have a bluetooth keyboard, on the logitech keyboard in the US the grave key is just below the Esc key. Grave not used much in coding or even writing documents, it seems to me, changing the default vimrc file to map the grave key to Esc would make usability much better.

Yes, the user can create a .vimrc file to do this. It would just be nice to have this mapping by default.

**Comment by mars0i** [comment]
\` is also important in markdown, which is commonly used on sites such as ... `github`.

**Comment by nicolasbraun** [comment]
We agree with the above comments.
The idea of a gesture to Esc is pretty nice, I will add it to the backlog

**Comment by nicolasbraun** [comment]
@broomdodger what would be the best gesture for you ?

Note: we will leave the mapping to \ if you are using and external keyboard
