### ISSUE TITLE
Multi-character mappings no longer work

### ISSUE THREAD

**Issue by mon10a** [applidium/Vim#30]
It no longer works to map 2 characters to a command or function. For example:

```
imap jj <esc> no longer works to map "jj" to the <escape> key. 
```

Similarly, mapleader no longer works. For example:

```
let mapleader = "," does not work to allow "," to trigger another defined command or function.
```

Both of these worked fine a while ago and I can't remember if they broke in the last update of Vim for iPad or if it was after an iOS update.

Would it be possible to fix these?

**Comment by nicolasbraun** [comment]
related to #10 ?

**Comment by mon10a** [comment]
Thanks for looking at this. 

My issue may be related to #10, but I have not tested map or nnoremap (both mentioned in #10). 

My narrower issue was that imap no longer works. This means that you can't substitute 'jj' or 'jk' or one of the other common alternatives for the escape character.

**Comment by mon10a** [comment]
Sorry, did not mean to close the issue.

**Comment by nicolasbraun** [comment]
Yeah I saw, you cannot validate (enter does nothing) the imap command, do you experience the same behavior?

**Comment by nicolasbraun** [comment]
@laviallb notice that after setting this imap command taping the letter `j` lags a bit and the cursor takes time before moving to the end of line.
