### ISSUE TITLE
App Lidium link 404

### ISSUE THREAD

**Issue by felippenardi** [applidium/Vim#31]
The link on the repository description is broken: 404 Not Found
http://applidium.com/en/applications/vim/

**Comment by felippenardi** [comment]
@nicolasbraun Could you explain why you are closing this?

**Comment by nicolasbraun** [comment]
@felippenardi  my bad, I checked in the code for this string and couldn't find it. I guess I was a bit to quick 🚀 , this is fix now. Thanks for spotting it.

**Comment by felippenardi** [comment]
You got it! Thanks @nicolasbraun :)
