### ISSUE TITLE
:set guifont=* doesn't list fonts

### ISSUE THREAD

**Issue by mars0i** [applidium/Vim#32]
`:set guifont=*` doesn't do anything, but it is possible to make some font changes using `:set guifont`.  However, it's difficult to experiment with different fonts without knowing what fonts are available.

(This is with vim 7.3, iOS 8.3 on an iPad mini.  On the mini, at least, the default font is very small, and there are dropped pixels in some of the characters, making them hard to read.  I'm hoping to set the font to a larger, more easily readable one.)

Thank you for porting Vim to iOS!

**Comment by kenny-evitt** [comment]
@mars0i What fonts are available?

**Comment by mars0i** [comment]
Sorry--it's been a while since I experimented with this.  I think I tried some standard fonts names like "Helvitica" or "Times New Roman".

**Comment by kenny-evitt** [comment]
@mars0i No worries. I found [iOS Fonts](http://iosfonts.com/) and I tried one, *American Typewriter*. The text definitely looked different, but, unfortunately, my text is even more unreadable than with the default font [#34].

**Comment by mars0i** [comment]
I'm not sure whether it's appropriate to mention this here (feel free to delete the comment, applidium), but there's also an iOS vi clone called Buffer.  I would rather use Vim, other things being equal.

**Comment by kenny-evitt** [comment]
@mars0i I have Buffer too but I just downloaded *Vim* because Buffer is missing a lot of commands. One thing it does have that it is (mostly) amazing is the custom keyboard, particularly the row of 'swipey' keys above the regular keyboard:

![img_1387](https://cloud.githubusercontent.com/assets/1461730/17008722/f334194e-4ec1-11e6-895d-88946fd31920.jpg)

**Comment by mars0i** [comment]
Ah, I understand about Vim commands.  Yeah, I like Buffer's keyboard.  I have an iPad extension keyboard that made it very difficult to type Esc. :-)

**Comment by nicolasbraun** [comment]
This issues contains several topics.
The custom font rendering is fixed in next release
