### ISSUE TITLE
Allow default of fewer, larger lines?

### ISSUE THREAD

**Issue by mars0i** [applidium/Vim#33]
I can change the font size with e.g. `:set guifont=Monaco:h18`.  However, with larger sizes, there is no built-in font, so Vim has to generate a large font from a small-font fontspec.  This looks very ugly on the screen.  Unfortunately, on an iPad mini, the default font is very small and difficult to read, so either way, I get a font that's hard to read.  (On a full-sized iPad, the default is probably fine.)

I'm wondering whether it would be possible to set the default display size in such a way as to make everything larger--larger, fewer lines of text.  The idea is that on a smaller device such as a mini, `Monaco:h12`, for example, would look as large as `Monaco:h18` does now.  On a regular iPad, the size of lines should presumably remain the same as it is now.

This option might be configurable, in theory, or it could depend on the device model.
(Again, thanks for porting Vim to iOS.)

**Comment by nicolasbraun** [comment]
Here is how it renders for next release.
We cill not implement a dynamic font size based on the device size, you can change it pretty easily.

![simulator screen shot 24 aug 2017 11 45 20](https://user-images.githubusercontent.com/1089363/29660505-d08ff454-88c1-11e7-84b7-bf953b111b93.png)
