### ISSUE TITLE
Fonts or text are mangled and mostly unreadable

### ISSUE THREAD

**Issue by kenny-evitt** [applidium/Vim#34]
The default font is difficult to read as it appears to be mangled, 'corrupted', or otherwise simply rendering poorly. I just installed the latest version of the app. I'm running iOS 9.3.2.

**Comment by kenny-evitt** [comment]
Here's a screenshot of the output of `:version`:

![image](https://cloud.githubusercontent.com/assets/1461730/16985342/bb6b2972-4e4d-11e6-9cf0-085f5367d4fd.png)

**Comment by kenny-evitt** [comment]
The font in the above screenshot is *American Typewriter* at 11 points.

**Comment by kenny-evitt** [comment]
@nicolasbraun Any chance I could test the next release, e.g. via TestFlight?

**Comment by nicolasbraun** [comment]
Yeah @kenny-evitt you can register to the beta here https://goo.gl/kV5yTP
Next version is currently under Apple's review

Cheerz

**Comment by kenny-evitt** [comment]
@nicolasbraun Thanks!
