### ISSUE TITLE
Secure connection on website fails

### ISSUE THREAD

**Issue by psjnek** [applidium/Vim#43]
![image](https://user-images.githubusercontent.com/94064167/211022519-c2c713d8-8572-4a26-94cb-9763d0f934b0.png)

**Comment by psjnek** [comment]
@brammool
This error still occurs.

**Comment by brammool** [comment]
Why are you asking me?  Doesn't look like anything under my control.

**Comment by psjnek** [comment]
> Why are you asking me? Doesn't look like anything under my control.

Sorry, my bad.
